# Generated by Django 4.1.7 on 2023-03-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_delete_orderbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderbook',
            fields=[
                ('orderbook_id', models.IntegerField(blank=True, null=True)),
                ('ordernumber', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('deliverytime', models.DateField(blank=True, null=True)),
                ('price_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'orderbook',
                'managed': False,
            },
        ),
    ]
