# Generated by Django 4.1.7 on 2023-03-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumodel',
            name='order',
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='item',
            field=models.CharField(max_length=255, verbose_name='Пункт меню'),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='name',
            field=models.CharField(default='main', max_length=255, verbose_name='Наименование меню'),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Menu.menumodel', verbose_name='Родительский пункт меню'),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Ссылка'),
        ),
    ]
